version: '3.7'

services:
  # Dependancies
  minio:
    image: ${REGISTRY}minio/minio
    environment:
      MINIO_ACCESS_KEY: al_storage_key
      MINIO_SECRET_KEY: "${FILESTORE_PASSWORD}"
    command: server /data
    networks: [core]
    volumes:
    - filestore:/data
    restart: on-failure

  elasticsearch:
    image: ${REGISTRY}docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      - logger.level=WARN
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "ES_JAVA_OPTS=-Xms512m -Xmx${ELASTIC_MAX_MEM}m"
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail -u elastic:${ELASTIC_PASSWORD} localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s
        retries: 3
    networks: [core]
    volumes:
      - datastore:/usr/share/elasticsearch/data
    restart: on-failure

  redis:
    image: ${REGISTRY}redis
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure
    networks: [core]

  nginx:
    image: ${REGISTRY}cccs/nginx-ssl
    ports:
      - '443:443'
    environment:
      - DOLLAR=$$
      - UI_HOST=al_ui
      - SOCKET_HOST=al_socketio
      - FQDN=${DOMAIN}
      - MAX_BODY_SIZE=100M
      - TEMPLATE=minimal
    volumes:
      - ${COMPOSE_ROOT}/config/nginx.crt:/etc/ssl/nginx.crt:ro
      - ${COMPOSE_ROOT}/config/nginx.key:/etc/ssl/nginx.key:ro
    networks:
      - core
      - external
    restart: on-failure


  # Start the core services
  # Alerter
  al_alerter:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [core]
    restart: on-failure
    command: python -m assemblyline_core.alerter.run_alerter

  # Expiry
  al_expiry:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [core]
    restart: on-failure
    command: python -m assemblyline_core.expiry.run_expiry

  # Hearbeat manager
  al_heartbeat:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [core]
    restart: on-failure
    command: python -m assemblyline_core.metrics.run_heartbeat_manager

  # Workflow
  al_workflow:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [core]
    restart: on-failure
    command: python -m assemblyline_core.workflow.run_workflow

  # Watcher
  al_watcher:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [core]
    restart: on-failure
    command: python -m assemblyline_core.watcher.run_watcher

  al_scaler:
    build:
      context: privilege-core-image
      args:
        version: ${CORE_VERSION}
        registry: ${REGISTRY}
      cache_from:
        - cccs/assemblyline-core:${CORE_VERSION}
    privileged: true
    env_file: [".env"]
    environment:
      FILE_UPDATE_VOLUME: ${UPDATE_DATA_PATH}
      FILE_UPDATE_DIRECTORY: /mount/update_root/
    volumes:
      - ${UPDATE_DATA_PATH}:/mount/update_root/
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock  # NOTE, this container has access to docker socket (this is like root)
    networks: [core]
    restart: on-failure
    command: python -m assemblyline_core.scaler.run_scaler

  al_updater:
    build:
      context: privilege-core-image
      args:
        version: ${CORE_VERSION}
        registry: ${REGISTRY}
      cache_from:
        - cccs/assemblyline-core:${CORE_VERSION}
    privileged: true
    env_file: [".env"]
    environment:
      FILE_UPDATE_VOLUME: ${UPDATE_DATA_PATH}
      FILE_UPDATE_DIRECTORY: /mount/update_root/
    volumes:
      - ${UPDATE_DATA_PATH}:/mount/update_root/
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock  # NOTE, this container has access to docker socket (this is like root)
    command: python3 -m assemblyline_core.updater.run_updater
    networks: [core]
    restart: on-failure

  al_dispatcher_files:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [core]
    restart: on-failure
    command: python -m assemblyline_core.dispatching.run_files

  al_dispatcher_submissions:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [core]
    restart: on-failure
    command: python -m assemblyline_core.dispatching.run_submissions

  # Ingester Processes
  al_ingester_ingest:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [core]
    restart: on-failure
    command: python -m assemblyline_core.ingester.run_ingest

  al_ingester_internal:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [core]
    restart: on-failure
    command: python -m assemblyline_core.ingester.run_internal

  al_ingester_submit:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [core]
    restart: on-failure
    command: python -m assemblyline_core.ingester.run_submit

  # Service server
  al_service_server:
    image: ${REGISTRY}cccs/assemblyline-service-server:${SERVICE_SERVER_VERSION}
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks:
      - core
      - svc
    depends_on: [elasticsearch, redis]
    env_file: [".env"]
    environment:
      SERVICE_API_AUTH_KEY: ${SERVICE_API_KEY}
    command: "python -m assemblyline_service_server.app"
    restart: on-failure

  # UI
  al_ui:
    image: ${REGISTRY}cccs/assemblyline-ui:${UI_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    command: python3 -m assemblyline_ui.app
    networks: [core, external]
    restart: on-failure

  # SocketIO Server
  al_socketio:
    image: ${REGISTRY}cccs/assemblyline-socketio:${UI_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    command: python3 -m assemblyline_ui.socketsrv
    networks: [core]
    restart: on-failure

networks:
  core:
    internal: true
  external:
    internal: false
  svc:
    name: svc
    internal: true

volumes:
  filestore:
  datastore:
