elasticsearch.hosts: ${ELASTIC_HOSTS}
elasticsearch.password: ${ELASTIC_PASSWORD}
elasticsearch.username: ${ELASTIC_USERNAME}

logging.quiet: true

server.basePath: /kibana
server.rewriteBasePath: true
server.name: kibana
server.host: "0.0.0.0"
server.publicBaseUrl: https://localhost/kibana