core:
  alerter:
    delay: 0
  metrics:
    apm_server:
      server_url: http://apm_server:8200/
    elasticsearch:
      hosts: ["elastic:password_465@elasticsearch"]
    redis:
      host: redis
      port: 6379
  redis:
    nonpersistent:
      host: redis
      port: 6379
    persistent:
      host: redis
      port: 6379

datastore:
  hosts: ["elastic:password_465@elasticsearch"]

filestore:
  cache: ["s3://al_storage_key:password_123@minio:9000?s3_bucket=al-cache&use_ssl=False"]
  storage: ["s3://al_storage_key:password_132@minio:9000?s3_bucket=al-storage&use_ssl=False"]

logging:
  log_level: WARNING
  log_to_console: true
  log_to_file: false
  log_to_syslog: false