core:
  alerter:
    delay: 0
  metrics:
    apm_server:
      server_url: null
    elasticsearch:
      hosts: []
    redis:
      host: redis
      port: 6379
  scaler:
    cpu_overallocation: 8.0
    service_defaults:
      backlog: 10
      shrink: 20
      min_instances: 1
      environment:
        - name: SERVICE_API_KEY
          value: ${SERVICE_API_KEY}
        - name: SERVICE_API_HOST
          value: 'http://service-server:5003'
  redis:
    nonpersistent:
      host: redis
      port: 6379
    persistent:
      host: redis
      port: 6379

datastore:
  hosts: ["elastic:${ELASTIC_PASSWORD}@elasticsearch"]

filestore:
  cache: ["s3://al_storage_key:${FILESTORE_PASSWORD}@minio:9000?s3_bucket=al-cache&use_ssl=False"]
  storage: ["s3://al_storage_key:${FILESTORE_PASSWORD}@minio:9000?s3_bucket=al-storage&use_ssl=False"]

logging:
  log_level: WARNING
  log_as_json: false
  log_to_console: true
  log_to_file: false
  log_to_syslog: false