version: '2.4'

services:
  # Dependancies
  minio:
    image: ${REGISTRY}minio/minio
    environment:
      MINIO_ACCESS_KEY: al_storage_key
      MINIO_SECRET_KEY: "${FILESTORE_PASSWORD}"
    command: server /data
    networks: [al_core]
    volumes:
    - filestore:/data
    restart: on-failure

  elasticsearch:
    image: ${REGISTRY}docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      - logger.level=WARN
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "ES_JAVA_OPTS=-Xms512m -Xmx${ELASTIC_MAX_MEM}m"
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail -u elastic:${ELASTIC_PASSWORD} localhost:9200/_cluster/health || exit 1"]
        interval: 30s
        timeout: 30s
        retries: 3
    networks: [al_core]
    volumes:
      - datastore:/usr/share/elasticsearch/data
    restart: on-failure

  redis:
    image: ${REGISTRY}redis
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure
    networks: [al_core]

  nginx:
    image: ${REGISTRY}cccs/nginx-ssl
    ports:
      - '443:443'
    environment:
      - DOLLAR=$$
      - UI_HOST=al_ui
      - SOCKET_HOST=al_socketio
      - FQDN=${DOMAIN}
      - MAX_BODY_SIZE=100M
      - TEMPLATE=minimal
    volumes:
      - ${COMPOSE_ROOT}/config/nginx.crt:/etc/ssl/nginx.crt:ro
      - ${COMPOSE_ROOT}/config/nginx.key:/etc/ssl/nginx.key:ro
    networks:
      - al_core
      - al_external
    restart: on-failure
    depends_on:
      al_ui:
        condition: service_started


  # Start the core services
  # Alerter
  al_alerter:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [al_core]
    restart: on-failure
    command: python -m assemblyline_core.alerter.run_alerter
    depends_on:
      elasticsearch:
        condition: service_healthy

  # Expiry
  al_expiry:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [al_core]
    restart: on-failure
    command: python -m assemblyline_core.expiry.run_expiry
    depends_on:
      elasticsearch:
        condition: service_healthy

  # Hearbeat manager
  al_heartbeat:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [al_core]
    restart: on-failure
    command: python -m assemblyline_core.metrics.run_heartbeat_manager
    depends_on:
      elasticsearch:
        condition: service_healthy

  # Workflow
  al_workflow:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [al_core]
    restart: on-failure
    command: python -m assemblyline_core.workflow.run_workflow
    depends_on:
      elasticsearch:
        condition: service_healthy

  # Watcher
  al_watcher:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [al_core]
    restart: on-failure
    command: python -m assemblyline_core.watcher.run_watcher
    depends_on:
      elasticsearch:
        condition: service_healthy

  al_scaler:
    build:
      context: privilege-core-image
      args:
        version: ${CORE_VERSION}
        registry: ${REGISTRY}
      cache_from:
        - ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    privileged: true
    env_file: [".env"]
    environment:
      FILE_UPDATE_VOLUME: ${UPDATE_DATA_PATH}
      FILE_UPDATE_DIRECTORY: /mount/update_root/
    volumes:
      - ${UPDATE_DATA_PATH}:/mount/update_root/
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock  # NOTE, this container has access to docker socket (this is like root)
    networks: [al_core]
    restart: on-failure
    command: python -m assemblyline_core.scaler.run_scaler
    depends_on:
      elasticsearch:
        condition: service_healthy

  al_updater:
    build:
      context: privilege-core-image
      args:
        version: ${CORE_VERSION}
        registry: ${REGISTRY}
      cache_from:
        - ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    privileged: true
    env_file: [".env"]
    environment:
      FILE_UPDATE_VOLUME: ${UPDATE_DATA_PATH}
      FILE_UPDATE_DIRECTORY: /mount/update_root/
    volumes:
      - ${UPDATE_DATA_PATH}:/mount/update_root/
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock  # NOTE, this container has access to docker socket (this is like root)
    command: python3 -m assemblyline_core.updater.run_updater
    networks: [al_core, al_external]
    restart: on-failure
    depends_on:
      elasticsearch:
        condition: service_healthy

  al_dispatcher_files:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [al_core]
    restart: on-failure
    command: python -m assemblyline_core.dispatching.run_files
    depends_on:
      elasticsearch:
        condition: service_healthy

  al_dispatcher_submissions:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [al_core]
    restart: on-failure
    command: python -m assemblyline_core.dispatching.run_submissions
    depends_on:
      elasticsearch:
        condition: service_healthy

  # Ingester Processes
  al_ingester_ingest:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [al_core]
    restart: on-failure
    command: python -m assemblyline_core.ingester.run_ingest
    depends_on:
      elasticsearch:
        condition: service_healthy

  al_ingester_internal:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [al_core]
    restart: on-failure
    command: python -m assemblyline_core.ingester.run_internal
    depends_on:
      elasticsearch:
        condition: service_healthy

  al_ingester_submit:
    image: ${REGISTRY}cccs/assemblyline-core:${CORE_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [al_core]
    restart: on-failure
    command: python -m assemblyline_core.ingester.run_submit
    depends_on:
      elasticsearch:
        condition: service_healthy

  # Service server
  al_service_server:
    image: ${REGISTRY}cccs/assemblyline-service-server:${SERVICE_SERVER_VERSION}
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks:
      - al_core
      - al_registration
    depends_on: [elasticsearch, redis]
    env_file: [".env"]
    environment:
      SERVICE_API_AUTH_KEY: ${SERVICE_API_KEY}
    command: "python -m assemblyline_service_server.app"
    restart: on-failure
    depends_on:
      elasticsearch:
        condition: service_healthy

  # UI
  al_ui:
    image: ${REGISTRY}cccs/assemblyline-ui:${UI_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [al_core, al_external]
    restart: on-failure
    depends_on:
      elasticsearch:
        condition: service_healthy

  # SocketIO Server
  al_socketio:
    image: ${REGISTRY}cccs/assemblyline-socketio:${UI_VERSION}
    env_file: [".env"]
    volumes:
      - ${COMPOSE_ROOT}/config/config.yml:/etc/assemblyline/config.yml:ro
    networks: [al_core]
    restart: on-failure
    depends_on:
      elasticsearch:
        condition: service_healthy

networks:
  al_core:
    name: al_core
    internal: true
  al_external:
    name: al_external
    internal: false
  al_registration:
    name: al_registration
    internal: true

volumes:
  filestore:
  datastore:
